import React from "react";
import Head from "next/head";
import Header from "@/componenet/header/header";
import Footer from "@/componenet/footer/footer";

function index(props) {
  const { children } = props;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/iconAssamedia.svg" />
      </Head>
      <div>
        <Header />
        {children}
        <Footer/>
      </div>
    </>
  );
}

export default index;
